# ==============================================================================
# Ledgio — Automated Runtime Browser Regression Test Runner
# Usage: powershell -ExecutionPolicy Bypass -File scripts\test_runtime_gate.ps1
# ==============================================================================

$ErrorActionPreference = "Stop"

$port = 8099
$baseDir = Split-Path -Parent $PSScriptRoot
if (-not $baseDir) { $baseDir = "." }

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  Ledgio Milestone 4.1: Runtime Browser Regression Suite  " -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# 1. Start HTTP server in background job
$listener = New-Object System.Net.HttpListener
$listener.Prefixes.Add("http://127.0.0.1:$port/")
$listener.Start()
Write-Host "Local HTTP Server running on http://127.0.0.1:$port/" -ForegroundColor Green

$serverJob = [powershell]::Create().AddScript({
    param($listener, $serverDir)
    try {
        while ($listener.IsListening) {
            $context = $listener.GetContext()
            $req = $context.Request
            $res = $context.Response
            
            $rawPath = $req.Url.LocalPath.TrimStart('/')
            if ([string]::IsNullOrWhiteSpace($rawPath)) { $rawPath = "index.html" }
            $filePath = [System.IO.Path]::GetFullPath((Join-Path $serverDir $rawPath))
            
            if ($filePath.StartsWith($serverDir, [System.StringComparison]::OrdinalIgnoreCase) -and (Test-Path $filePath -PathType Leaf)) {
                $ext = [System.IO.Path]::GetExtension($filePath).ToLower()
                $contentType = switch ($ext) {
                    ".html" { "text/html; charset=utf-8" }
                    ".js"   { "application/javascript; charset=utf-8" }
                    ".css"  { "text/css; charset=utf-8" }
                    ".json" { "application/json; charset=utf-8" }
                    ".png"  { "image/png" }
                    ".jpg"  { "image/jpeg" }
                    ".svg"  { "image/svg+xml" }
                    Default { "application/octet-stream" }
                }
                $res.ContentType = $contentType
                $bytes = [System.IO.File]::ReadAllBytes($filePath)
                $res.ContentLength64 = $bytes.Length
                $res.OutputStream.Write($bytes, 0, $bytes.Length)
            } else {
                $res.StatusCode = 404
                $msg = [System.Text.Encoding]::UTF8.GetBytes("Not found: $rawPath")
                $res.ContentLength64 = $msg.Length
                $res.OutputStream.Write($msg, 0, $msg.Length)
            }
            $res.OutputStream.Close()
        }
    } catch {}
}).AddArgument($listener).AddArgument($baseDir)

$asyncHandle = $serverJob.BeginInvoke()

# 2. Run Edge Headless
$edgePath = "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
$outTxt = Join-Path $baseDir "edge_test_result.txt"
if (Test-Path $outTxt) { Remove-Item $outTxt -Force }

$userDataDir = "C:\Users\stand\AppData\Local\Temp\edge_test_user_data_regression"
if (Test-Path $userDataDir) { Remove-Item -Recurse -Force $userDataDir }

$edgeArgs = @(
    "--headless=new",
    "--virtual-time-budget=8000",
    "--dump-dom",
    "--user-data-dir=$userDataDir",
    "--no-first-run",
    "--no-default-browser-check",
    "http://127.0.0.1:$port/tests/headless_regression.html"
)

Write-Host "`nLaunching Edge Headless to run interactive DOM regression test..." -ForegroundColor Yellow
$proc = Start-Process -FilePath $edgePath -ArgumentList $edgeArgs -PassThru -NoNewWindow -RedirectStandardOutput $outTxt
$exited = $proc.WaitForExit(15000)

if (-not $exited) {
    $proc.Kill()
    Write-Host "Edge timed out!" -ForegroundColor Red
}

# 3. Shutdown Server
$listener.Stop()
$serverJob.Dispose()

# 4. Analyze Results
if (-not (Test-Path $outTxt)) {
    throw "No output file generated by Edge!"
}

$domOutput = [System.IO.File]::ReadAllText($outTxt, [System.Text.Encoding]::UTF8)

# Clean up temp output file
Remove-Item $outTxt -Force -ErrorAction SilentlyContinue

Write-Host "`n=== RUNTIME ASSERTION LOG ===" -ForegroundColor Cyan
$logMatches = [regex]::Matches($domOutput, '<li class="(pass|fail)">([^<]+)</li>')
$passCount = 0
$failCount = 0

foreach ($m in $logMatches) {
    $status = $m.Groups[1].Value
    $text = [System.Net.WebUtility]::HtmlDecode($m.Groups[2].Value)
    if ($status -eq "pass") {
        Write-Host "  $text" -ForegroundColor Green
        $passCount++
    } else {
        Write-Host "  $text" -ForegroundColor Red
        $failCount++
    }
}

Write-Host "`n==========================================================" -ForegroundColor Cyan
if ($domOutput -match 'data-status="PASSED"') {
    Write-Host "  >>> ALL RUNTIME REGRESSION GATES PASSED ($passCount passed, 0 failed) <<<" -ForegroundColor Green
    Write-Host "==========================================================" -ForegroundColor Cyan
    exit 0
} else {
    Write-Host "  >>> RUNTIME REGRESSION GATES FAILED ($passCount passed, $failCount failed) <<<" -ForegroundColor Red
    Write-Host "==========================================================" -ForegroundColor Cyan
    exit 1
}
